// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class BussinessMasterBLL
    {
        private BussinessMasterTableAdapter _BussinessMasterAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public int AddBussiness(string sBussinessName, string sBussinessDesc, bool bBussinessStatus)
        {
            int? bussinessID = 0;
            this.Adapter.Insert(ref bussinessID, sBussinessName, sBussinessDesc, new bool?(bBussinessStatus));
            return bussinessID.Value;
        }
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool DeleteBussiness(int iBussinessID)
        {
            try
            {
                this.Adapter.Delete(new int?(iBussinessID));
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.BussinessMasterDataTable GetAllDetail()
        {
            return this.Adapter.GetData();
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CloudAccountDA.BussinessMasterDataTable GetDataByBussinessID(int iBussinessID)
        {
            return this.Adapter.GetDataByBussinessID(new int?(iBussinessID));
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CloudAccountDA.BussinessMasterDataTable GetDataByBussinessName(string sBussinessName)
        {
            return this.Adapter.GetDataByBussinessName(sBussinessName);
        }
        
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public bool UpdateBussiness(int iBussinessID, string sBussinessName, string sBussinessDesc, bool bBussinessStatus)
        {
            try
            {
                this.Adapter.Update(new int?(iBussinessID), sBussinessName, sBussinessDesc, new bool?(bBussinessStatus));
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        protected BussinessMasterTableAdapter Adapter
        {
            get
            {
                if (this._BussinessMasterAdapter == null)
                {
                    return new BussinessMasterTableAdapter();
                }
                return this._BussinessMasterAdapter;
            }
        }
    }
}
