// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class CreditDefaultTermsMasterBLL
    {
        private CreditDefaultTermsMasterTableAdapter _CreditDefaultTermsMasterAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public int AddCreditDefaultTerms(int iCompanyID, string sDefaultTerms)
        {
            int? creditDefaultTermsID = 0;
            this.Adapter.Insert(ref creditDefaultTermsID, new int?(iCompanyID), sDefaultTerms);
            return creditDefaultTermsID.Value;
        }
        
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool DeleteByCompany(int iCompanyID)
        {
            try
            {
                this.Adapter.DeleteByCompanyID(new int?(iCompanyID));
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool DeleteCreditDefaultTerms(int iCreditDefaultTermsID)
        {
            try
            {
                this.Adapter.Delete(new int?(iCreditDefaultTermsID));
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.CreditDefaultTermsMasterDataTable GetAllDetail()
        {
            return this.Adapter.GetData();
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CloudAccountDA.CreditDefaultTermsMasterDataTable GetDataByCompanyID(int iCompanyID)
        {
            return this.Adapter.GetDataByCompanyID(new int?(iCompanyID));
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CloudAccountDA.CreditDefaultTermsMasterDataTable GetDataByCreditDefaultTerms(int iCreditDefaultTermsID)
        {
            return this.Adapter.GetDataByCreditDefaultTermsID(new int?(iCreditDefaultTermsID));
        }
        
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public bool UpdateCreditDefaultTerms(int iCreditDefaultTermsID, int iCompanyID, string sDefaultTerms)
        {
            try
            {
                this.Adapter.Update(new int?(iCreditDefaultTermsID), new int?(iCompanyID), sDefaultTerms);
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        protected CreditDefaultTermsMasterTableAdapter Adapter
        {
            get
            {
                if (this._CreditDefaultTermsMasterAdapter == null)
                {
                    return new CreditDefaultTermsMasterTableAdapter();
                }
                return this._CreditDefaultTermsMasterAdapter;
            }
        }
    }
}
