// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class FeatureCategoryMasterBLL
    {
        private FeatureCategoryMasterTableAdapter _FeatureCategoryMasterAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public int AddFeatureCategory(string sFeatureCategoryName, string sFeatureCategoryDesc, bool bShowOnHomePage, bool bFeatureCategoryStatus)
        {
            int? featureCategoryID = 0;
            this.Adapter.Insert(ref featureCategoryID, sFeatureCategoryName, sFeatureCategoryDesc, new bool?(bShowOnHomePage), new bool?(bFeatureCategoryStatus));
            return featureCategoryID.Value;
        }
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool DeleteFeatureCategory(int iFeatureCategoryID)
        {
            try
            {
                this.Adapter.Delete(new int?(iFeatureCategoryID));
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.FeatureCategoryMasterDataTable GetAllDetail()
        {
            return this.Adapter.GetData();
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CloudAccountDA.FeatureCategoryMasterDataTable GetDataByFeatureCategoryID(int iFeatureCategoryID)
        {
            return this.Adapter.GetDataByFeatureCategoryID(new int?(iFeatureCategoryID));
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CloudAccountDA.FeatureCategoryMasterDataTable GetDataByFeatureCategoryName(string sFeatureCategoryName)
        {
            return this.Adapter.GetDataByFeatureCategoryName(sFeatureCategoryName);
        }
        
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public bool UpdateFeatureCategory(int iFeatureCategoryID, string sFeatureCategoryName, string sFeatureCategoryDesc, bool bShowOnHomePage, bool bFeatureCategoryStatus)
        {
            try
            {
                this.Adapter.Update(new int?(iFeatureCategoryID), sFeatureCategoryName, sFeatureCategoryDesc, new bool?(bShowOnHomePage), new bool?(bFeatureCategoryStatus));
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        protected FeatureCategoryMasterTableAdapter Adapter
        {
            get
            {
                if (this._FeatureCategoryMasterAdapter == null)
                {
                    return new FeatureCategoryMasterTableAdapter();
                }
                return this._FeatureCategoryMasterAdapter;
            }
        }
    }
}
