// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class LatePaymentReminderTemplateBLL
    {
        private LatePaymentReminderTemplateTableAdapter _LatePaymentReminderTemplateAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public int AddLatePaymentReminder(int iCompanyID, int iReminder, bool bEnable, int iDays, string sLatePaymentReminderSubject, string sLatePaymentReminderBody)
        {
            int? latePaymentReminderID = 0;
            this.Adapter.Insert(ref latePaymentReminderID, new int?(iCompanyID), new int?(iReminder), new bool?(bEnable), new int?(iDays), sLatePaymentReminderSubject, sLatePaymentReminderBody);
            return latePaymentReminderID.Value;
        }
        
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool DeleteByCompanyID(int iCompanyID)
        {
            try
            {
                this.Adapter.DeleteByCompanyID(new int?(iCompanyID));
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool DeleteLatePaymentReminder(int iLatePaymentReminderID)
        {
            try
            {
                this.Adapter.Delete(new int?(iLatePaymentReminderID));
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.LatePaymentReminderTemplateDataTable GetAllDetail()
        {
            return this.Adapter.GetData();
        }
        
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CloudAccountDA.LatePaymentReminderTemplateDataTable GetDataByCompanyID(int iCompanyID, int iReminder)
        {
            return this.Adapter.GetDataByCompanyID(new int?(iCompanyID), new int?(iReminder));
        }
        
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public bool UpdateLatePaymentReminder(int iLatePaymentReminderID, int iCompanyID, int iReminder, bool bEnable, int iDays, string sLatePaymentReminderSubject, string sLatePaymentReminderBody)
        {
            try
            {
                this.Adapter.Update(new int?(iLatePaymentReminderID), new int?(iCompanyID), new int?(iReminder), new bool?(bEnable), new int?(iDays), sLatePaymentReminderSubject, sLatePaymentReminderBody);
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        
        protected LatePaymentReminderTemplateTableAdapter Adapter
        {
            get
            {
                if (this._LatePaymentReminderTemplateAdapter == null)
                {
                    return new LatePaymentReminderTemplateTableAdapter();
                }
                return this._LatePaymentReminderTemplateAdapter;
            }
        }
    }
}
