// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class PasswordQuestionBLL
    {
        private aspnet_MembershipTableAdapter _MemberAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.aspnet_MembershipDataTable GetAllPasswordQuestion(string sQuestion)
        {
            return this.Adapter.GetData(sQuestion);
        }
        
        protected aspnet_MembershipTableAdapter Adapter
        {
            get
            {
                if (this._MemberAdapter == null)
                {
                    return new aspnet_MembershipTableAdapter();
                }
                return this._MemberAdapter;
            }
        }
    }
}
