// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class ReportItemSalesBLL
    {
        private ReportItemSalesTableAdapter _ReportItemSalesAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.ReportItemSalesDataTable GetData(int iItemID, string sStatus, DateTime? dtFromDate, DateTime? dtToDate)
        {
            return this.Adapter.GetData(new int?(iItemID), sStatus, dtFromDate, dtToDate);
        }
        
        protected ReportItemSalesTableAdapter Adapter
        {
            get
            {
                if (this._ReportItemSalesAdapter == null)
                {
                    return new ReportItemSalesTableAdapter();
                }
                return this._ReportItemSalesAdapter;
            }
        }
    }
}
