// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class ReportProjectTaskBLL
    {
        private ReportProjectTaskTableAdapter _ReportProjectTaskAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.ReportProjectTaskDataTable GetData(int iCompanyID, int iTaskID, DateTime? dtFromDate, DateTime? dtToDate)
        {
            return this.Adapter.GetData(new int?(iCompanyID), new int?(iTaskID), dtFromDate, dtToDate);
        }
        
        protected ReportProjectTaskTableAdapter Adapter
        {
            get
            {
                if (this._ReportProjectTaskAdapter == null)
                {
                    return new ReportProjectTaskTableAdapter();
                }
                return this._ReportProjectTaskAdapter;
            }
        }
    }
}
