// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class ReportTasksInvoicedBLL
    {
        private ReportTasksInvoicedTableAdapter _ReportTasksInvoicedAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.ReportTasksInvoicedDataTable GetData(int iTaskID, string sStatus, DateTime? dtFromDate, DateTime? dtToDate)
        {
            return this.Adapter.GetData(new int?(iTaskID), sStatus, dtFromDate, dtToDate);
        }
        
        protected ReportTasksInvoicedTableAdapter Adapter
        {
            get
            {
                if (this._ReportTasksInvoicedAdapter == null)
                {
                    return new ReportTasksInvoicedTableAdapter();
                }
                return this._ReportTasksInvoicedAdapter;
            }
        }
    }
}
