// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class ReportTimesheetDetailsTaskBLL
    {
        private ReportTimesheetDetailsTaskTableAdapter _ReportTimesheetDetailsTaskAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.ReportTimesheetDetailsTaskDataTable GetData(int iCompanyID, int iTaskID, bool? bBilled, DateTime? dtFromDate, DateTime? dtToDate)
        {
            return this.Adapter.GetData(new int?(iCompanyID), new int?(iTaskID), bBilled, dtFromDate, dtToDate);
        }
        
        protected ReportTimesheetDetailsTaskTableAdapter Adapter
        {
            get
            {
                if (this._ReportTimesheetDetailsTaskAdapter == null)
                {
                    return new ReportTimesheetDetailsTaskTableAdapter();
                }
                return this._ReportTimesheetDetailsTaskAdapter;
            }
        }
    }
}
