// Generated by .NET Reflector from E:\Projects\Doyingo_Migration\Website\bin\DABL.dll
namespace DABL.BLL
{
    using DABL.DAL;
    using DABL.DAL.CloudAccountDATableAdapters;
    using System;
    using System.ComponentModel;
    
    public class UserBLL
    {
        private aspnet_UsersTableAdapter _UserAdapter;
        
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CloudAccountDA.aspnet_UsersDataTable GetAllDetail(string sUsername)
        {
            return this.Adapter.GetData(sUsername);
        }
        
        protected aspnet_UsersTableAdapter Adapter
        {
            get
            {
                if (this._UserAdapter == null)
                {
                    return new aspnet_UsersTableAdapter();
                }
                return this._UserAdapter;
            }
        }
    }
}
